In [2]:
import cv2
import numpy as np

In [41]:
#image=cv2.imread("peppers.jpg")
image=cv2.imread("satimg1.jpg")
print(image.shape)

(122, 413, 3)


In [44]:
cv2.imshow('original', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
#Preprocessing step
image=cv2.GaussianBlur(image,(7,7),0)

In [7]:
cv2.GaussianBlur?

In [45]:
vectorized=image.reshape(-1,3)
vectorized=np.float32(vectorized)

In [46]:
vectorized.shape

(50386, 3)

In [146]:
cv2.TERM_CRITERIA_MAX_ITER

1

( type, max_iter, epsilon )

In [11]:
criteria=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,
              10, 1.0)

In [12]:
criteria

(3, 10, 1.0)

In [47]:
ret,label,center=cv2.kmeans(vectorized,5,None,criteria,10,cv2.KMEANS_RANDOM_CENTERS)

In [15]:
cv2.kmeans?

In [28]:
center[label.flatten()]

array([[  36.04788208,   47.65000916,  178.51091003],
       [  36.04788208,   47.65000916,  178.51091003],
       [  36.04788208,   47.65000916,  178.51091003],
       ..., 
       [ 141.57711792,  200.96047974,  180.14567566],
       [ 141.57711792,  200.96047974,  180.14567566],
       [ 141.57711792,  200.96047974,  180.14567566]], dtype=float32)

In [49]:
res = center[label.flatten()]

In [30]:
res

array([[  36.04788208,   47.65000916,  178.51091003],
       [  36.04788208,   47.65000916,  178.51091003],
       [  36.04788208,   47.65000916,  178.51091003],
       ..., 
       [ 141.57711792,  200.96047974,  180.14567566],
       [ 141.57711792,  200.96047974,  180.14567566],
       [ 141.57711792,  200.96047974,  180.14567566]], dtype=float32)

In [103]:
np.ndarray.flatten?

In [50]:
segmented_image = res.reshape((image.shape))
segmented_image = segmented_image.astype(np.uint8)

In [51]:
label = label.reshape((image.shape[0],image.shape[1]))

In [52]:
cv2.imshow('segmented', segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [59]:
component = np.zeros(image.shape,np.uint8)
component[label == 1] = image[label == 1]

In [60]:
cv2.imshow('component', component)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
label == 4

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)